# Use the official Python image as the base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR .

RUN pip install --no-cache-dir Flask pymongo python-dotenv requests beautifulsoup4 flask-cors

# Copy the API source code into the container
COPY api/ .

# Command to run the API (adjust as per your entry point, e.g., app.py or manage.py)
CMD ["python", "app.py"]