version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
    depends_on:
      - datawarehouse
    networks:
      - app_network

  logic:
    build:
      context: .
      dockerfile: Dockerfile.logic
    ports:
      - "5001:5001/tcp"
    environment:
      MONGODB_URI: mongodb://palm:oil123!@datawarehouse:27017/palmoildatabase
      MONGODB_USERNAME: palm
      MONGODB_PASSWORD: oil123!
      FILE_PATH: '/app/data/PalmOil-UML-Oct-2024.xlsx'
      FLASK_ENV: development
    depends_on:
      - datawarehouse
    networks:
      - app_network

  datawarehouse:
    build:
      context: .
      dockerfile: Dockerfile.datawarehouse
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

networks:
  app_network:
