version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper