version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
    depends_on:
      - api
      - datawarehouse

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper

  datawarehouse:
    build:
      context: .
      dockerfile: Dockerfile.datawarehouse
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
